[package]
name = "message_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { git = "https://github.com/Sanae6/serenity-scope", branch = "current"}
tokio = { version = "1.42.0", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
futures = "0.3.31"
chrono = "0.4"